# Generated by Django 4.1.1 on 2022-10-19 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name="Qo'shilgan sana")),
                ('updated_at', models.DateTimeField(auto_now_add=True, verbose_name='Yangilangan sana')),
                ('name', models.CharField(max_length=250, verbose_name='Kurs nomi')),
            ],
            options={
                'verbose_name': 'Kurs',
                'verbose_name_plural': 'Kurslar',
                'db_table': 'courses',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name="Qo'shilgan sana")),
                ('updated_at', models.DateTimeField(auto_now_add=True, verbose_name='Yangilangan sana')),
                ('user_id', models.BigIntegerField(primary_key=True, serialize=False, verbose_name='Telegram ID raqami')),
                ('referral', models.CharField(blank=True, default=None, max_length=50, null=True, verbose_name='Referral')),
                ('full_name', models.CharField(max_length=255, verbose_name='F.I.SH')),
                ('phone', models.CharField(blank=True, default=None, max_length=50, verbose_name='Telefon')),
                ('username', models.CharField(blank=True, default=None, max_length=150, null=True, verbose_name='TG username')),
                ('offline_study', models.BooleanField(default=False, verbose_name="Offline o'qiydi")),
                ('registered', models.BooleanField(default=False, verbose_name="Botda ro'yxatdan o'tgan")),
                ('mediana', models.IntegerField(default=0, verbose_name='Mediana coin')),
                ('blocked', models.BooleanField(default=False, verbose_name='Botni bloklagan')),
                ('subscribed', models.ManyToManyField(blank=True, to='mediana.course', verbose_name='Botdan olgan kurslari')),
            ],
            options={
                'verbose_name': 'Foydalanuvchi',
                'verbose_name_plural': 'Foydalanuvchilar',
                'db_table': 'students',
            },
        ),
    ]
